# Generated by Django 4.0 on 2021-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManager', '0002_rename_city_number_hotel_id_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id_hotel',
            field=models.CharField(max_length=3),
        ),
    ]
